### ISSUE TITLE
Require python-irodsclient >=2.0.0

### ISSUE THREAD

**Issue by chStaiger** [UtrechtUniversity/iBridges#154]
Currently we account in our code for the dofferences between PRC v1.X and 2.X
Switch to PRC 2.X as a requirement in the toml.

**Comment by qubixes** [comment]
Which parts of the code are different? The error handling?

**Comment by chStaiger** [comment]
Yes exactly. The same functions from the PRC throw different errors. The only thing that is holding me a bit back is, that version 2.0.0 is pretty early and I would rather move to something like 2.0.1/2

**Comment by qubixes** [comment]
The latest version is technically 2.0.1! Personally, I don't think for now we should require it (yet). Perhaps we can document the differences that are maintained for now. Perhaps we can make >=2.0 the recommendation? The main issue I see is that we create conflicts for users when they somehow have a <2.0 requirement for python-irodsclient. Perhaps we can make the switch next year?

**Comment by chStaiger** [comment]
That is what I am doing . But strictly we would have to extend our integration tests to the two versions of the PRC ... 

So far I found mainly differences in our session ad I am willing to do the two tests manually. the docker integration pipeline takes always the latest version of the PRC.

**Comment by qubixes** [comment]
Yes, ideally we would run our tests against both versions (or even all versions of python-irodsclient). Perhaps doing it manually before every release would be good enough indeed.

**Comment by chStaiger** [comment]
Postponed.
