### ISSUE TITLE
Documentation (Python client): Session(irods_env_path) > Session(irods_env)

### ISSUE THREAD

**Issue by DorienHuijser** [UtrechtUniversity/iBridges#163]
**Describe the bug**

According to the documentation (README and readthedocs), the Session function requires an argument called `irods_env_path`:

```
from ibridges import Session
session = Session(irods_env_path="~/.irods/irods_environment.json", password="mypassword")
```

However this throws the error: 
> TypeError: Session.__init__() got an unexpected keyword argument 'irods_env_path'

After consulting `help(Session)`, I learned that the argument's name is `irods_env` instead. That should be updated in the documentation :)

```
from ibridges import Session
session = Session(irods_env="~/.irods/irods_environment.json", password="mypassword")
```

**Provide some information:**
 - OS: Windows 10
 - Software version or branch you are working on: Working in Anaconda Prompt (anaconda Command line client version 1.12.1)
 - python version: Python 3.11.5
 - iRODS version: iRods not installed as far as I know
 - python-irodsclient version (`python -c "import irods; print(irods.__version__)"` ): 2.0.1

**Comment by chStaiger** [comment]
Yes, at the moment it is a bit confusing. In the latest-greatest version in the dveleopment branch we switched the parameter to irods_env which can be a file path or a dictionary. In the official latest release ibridges1.1.6 it is still as mentioned in the tutorial. 

We are currently rewriting all the documentation.

**Comment by chStaiger** [comment]
It should be fixed in the develop branch for the next version
