### ISSUE TITLE
Some additions to the documentation

### ISSUE THREAD

**Issue by DorienHuijser** [UtrechtUniversity/iBridges#164]
Hello! I started testing iBridges today on my Windows 10 PC through Anaconda Prompt. I first looked at the readthedocs and the README, and only then discovered the jupyter notebook tutorials. 

Here's what I wrote down which could improve the documentation:

- [x] As a first-time user who started out with the CLI information in the README, it wasn't fully clear to me what exactly the iRods path is. In the README and readthedocs. `ibridges list` gives the entire path, but also includes `nluu12p/home/` in front of the path, but it is not 100% clear that you don't have to give that part of the path as an input (you can use `irods:name-of-folder/sub-folder/etc` immediately).
- [x] Paths: I only discovered how paths work in the jupyter notebook tutorials. It may be good to mention in the readthedocs / README that paths require forward slashes (not backward slashes as Windows gives) and that paths need quotes if there is a space in the path name. This is a super minor detail but still relevant for total noobs like me :)

Additional suggestions for documentation - if possible in iBridges:
- [x] Probably on your list already, but: provide tutorials for the CLI functionality
- [x] Information on how to _delete_ information from iRods (and subsequently from Yoda for Yoda users)
- [x] How to estimate the time it takes for data upload / download / synchronization? Can this be done with `dry_run`? This would maybe be beneficial for larger datasets

**Provide some information:**
- OS: Windows 10
- Software version or branch you are working on: Working in Anaconda Prompt (anaconda Command line client version 1.12.1)
- python version: Python 3.11.5
-  iRODS version: iRods not installed as far as I know
- python-irodsclient version (python -c "import irods; print(irods.__version__)" ): 2.0.1

**Comment by chStaiger** [comment]
The Path tutorial is updated and will preceed the "Working with data" Tutorial.
#165
What do you think about it?

**Comment by chStaiger** [comment]
Synchronising data:
Indeed with the dryrun, you will get a list of what needs to be added or updated and will give a user a feeling how long it may take. It is hard to give real time estimations since we are very dependent on Network performance here. By default there is a status bar for synchronisation and we are thinking of a `verbose` option for the upload and download functionality.

**Comment by chStaiger** [comment]
There is more information on how to work with the commandline interface on readthe docs
