### ISSUE TITLE
IrodsPath parts should use the absolute path.

### ISSUE THREAD

**Issue by chStaiger** [UtrechtUniversity/iBridges#168]
That does not seem to be logically:

```
In [17]: print(IrodsPath(session))
/nluu12p/home/research-test-christine

In [18]: print(IrodsPath(session).parts)
()
```

The parts attribute should use the absolute path of an IrodsPath instance.

**Comment by qubixes** [comment]
Actually, I remember now. That is what pathlib does as well, so it keeps the similarity between our implementation and pathlib. Probably better to keep it this way then?

**Comment by chStaiger** [comment]
Can we then let absolute_path return an IrodsPath. And rename it to absolute?

```

In [36]: tmp = Path(".")

In [37]: tmp.absolute
Out[37]: <bound method Path.absolute of PosixPath('.')>

In [38]: tmp.absolute()
Out[38]: PosixPath('/Users/staig001')

```
