### ISSUE TITLE
IrodsPath.parent should be calculated from absolute path

### ISSUE THREAD

**Issue by chStaiger** [UtrechtUniversity/iBridges#173]
My irods_home is "/nluu12p/home/research-test-christine" and I can instantiate it in three ways.
 
In [5]: print(IrodsPath(session).parent)
/nluu12p/home/research-test-christine
 
In [6]: print(IrodsPath(session, "~").parent)
/nluu12p/home/research-test-christine
 
In [7]: print(IrodsPath(session, session.home).parent)
/nluu12p/home
 
But only the last one will give me the correct parent.

**Comment by qubixes** [comment]
It's the old pathlib doing it's things again. I guess we're going to move further and further away from copying its behavior..

Will fix after #169 is merged.
