### ISSUE TITLE
"Silent" transfer

### ISSUE THREAD

**Issue by jjkoehorst** [UtrechtUniversity/iBridges#236]
**Is your feature request related to a problem? Please describe.**
When transferring a 1000+ files using Jupyter notebook there is a massive overview of the transfers performed.

**Describe the solution you'd like**
A more silent approach (either a silent=true) option that only prints something when there is an issue.

`download(session, irods_path=irods_path, local_path=local_path, silent=true)`

**Comment by qubixes** [comment]
Hi @jjkoehorst, which version of iBridges are you using? The latest version (1.0.1) will return an `Operations` object, which shouldn't be automatically printed by a Jupyter notebook. For the older versions of iBridges, you can simply do:

```python
_ = download(...)
```
Which should also skip printing the overview.

Let me know if that solves your problem.
