### ISSUE TITLE
overwrite does wrong checksum validation

### ISSUE THREAD

**Issue by jjkoehorst** [UtrechtUniversity/iBridges#245]
**Describe the bug**
When setting the overwrite it will do a checksum test but it does the sha2 checksum and not the md5 that is being used in the iRODS instance I have access to.

**To Reproduce**
Make sure your irods uses the md5 checksum
Download a file with overwrite...

```python
        if not (
            local_path.is_file() and (calc_checksum(irods_path) == calc_checksum(local_path))
        ):

# Will call

    if isinstance(filepath, IrodsPath):
        return filepath.checksum
    f_hash=sha256()
    memv=memoryview(bytearray(128*1024))
    with open(filepath, 'rb', buffering=0) as file:
        for item in iter(lambda : file.readinto(memv), 0):
            f_hash.update(memv[:item])
    return f"sha2:{str(base64.b64encode(f_hash.digest()), encoding='utf-8')}"
```

**Provide some information:**
 - OS: Mac osx
 - Software version or branch you are working on
 - python version 3.12.4
 - iRODS version 
 - python-irodsclient version (`python -c "import irods; print(irods.__version__)"` )

**Comment by qubixes** [comment]
@jjkoehorst Thanks for noticing this. I will work on this before our next release.
