### ISSUE TITLE
up_sync and down_sync set overwrite = True

### ISSUE THREAD

**Issue by chStaiger** [UtrechtUniversity/iBridges#253]
... even if the upload or download wants an overwrite = False.

We also need to add tests to check the overwrite flag.

**Comment by qubixes** [comment]
The question is how to solve it. Do we checksum it first to see if it is the same data, then throw an error? Or already throw an error regardless of whether they are the same?

I feel like the first option makes the most sense, but then you can't use it in combination with the ignore errors to skip the checksum altogether.

**Comment by chStaiger** [comment]
To be consistent with the icommands we need first check on name level and throw an error if the obj/file or coll/folder already exists. Then if there is an overwrite flag, we do the checksum checking.

**Comment by chStaiger** [comment]
Here an example:

```
cstaiger@integration:~$ cat hello.txt
hello world
cstaiger@integration:~$ iput -K hello.txt
cstaiger@integration:~$ echo "hello again" > hello.txt
cstaiger@integration:~$ cat hello.txt
hello again
cstaiger@integration:~$ iput -K hello.txt
remote addresses: 131.211.18.79 ERROR: putUtil: put error for /nluu12p/home/research-test-christine/hello.txt, status = -312000 status = -312000 OVERWRITE_WITHOUT_FORCE_FLAG
```
