### ISSUE TITLE
Reorganize files

### ISSUE THREAD

**Issue by qubixes** [UtrechtUniversity/iBridges#47]
Proposal:

- The ibridges package will be completely flat, no more subpackages (irodsconnector, utils)
- The following functions/classes will be available in the `__init__.py`:

- Session
- IrodsPath
- sync (#41)
- Tickets
- MetaData
- get_dataobject, get_collection, upload, download
- search

Specifically, we will keep all the functions/modules that will fall in the interactive category (#48) out of the `ibridges/_init__.py` to make sure that it is always clear that the functions there are to be used differently from the library functions.

- The functions `get_size`, `get_dataobject`, `get_collection`, `is_dataobject`, `is_collection`, `obj_replicas` are not really data_operations, so should be moved to a newly created `utils.py`.

**Comment by chStaiger** [comment]
It seems linked to #46
