### ISSUE TITLE
Guides result in 404

### ISSUE THREAD

**Issue by jnimoth** [UtrechtUniversity/iBridges#69]
Hi all! First, very cool to see progress with `iBridges`! 

I saw that the link to the Guides is not working (neither from Github nor PyPI).
For example here via Github (from PyPI it also gives a 404 error):

![ibridges_problem](https://github.com/UtrechtUniversity/iBridges/assets/109157914/f188b591-aea8-4b72-8e24-a31b7920f57a)

**Comment by qubixes** [comment]
Thanks @jnimoth! I'll just quickly fix the typos!
