### ISSUE TITLE
Export metadata to a file

### ISSUE THREAD

**Issue by chStaiger** [UtrechtUniversity/iBridges#72]
If users move their data to another storage system the metadata stays behind. It is a nice to have to have an export function such that the metadata is stored in a file.

Options to discuss:
- Recursive? Shall we make an option to export all metadata of all subcollections and data objects if the user wants the metadata of a collection?
- Which format shall we use?
    - https://en.wikipedia.org/wiki/BagIt
    - Json like in Yoda

**Comment by trel** [comment]
Just a consideration...

Do you want ALL the metadata?   There could be administrative or organizational metadata...
