### ISSUE TITLE
sync_data: combining `ignore_checksum = False` and `verify_checksum = True` always generates checksum mismatch error.

### ISSUE THREAD

**Issue by maartenschermer** [UtrechtUniversity/iBridges#84]
When executing `sync_data`, `ignore_checksum = False` prohibits checksum of iRODS objects being retrieved, causing the checksum verification (when `verify_checksum = True`) to compare the checksum of the downloaded file to `None`.

Two possible solutions:
+ Retrieve checksum on iRODS-objects when `verify_checksum = True`, regardless of the value of `ignore_checksum` (also requires changing the `__eq__` function of `FileObject`).
+ Do not accept the combination of `verify_checksum = True` and `ignore_checksum = False`.

**Comment by qubixes** [comment]
Another solution might be to simplify the API to have fewer arguments. There are currently three arguments involving checksums, and that might be a bit much to be honest. Perhaps this is a case where we should just always take the safe route, just so that unexpected things won't happen.

**Comment by maartenschermer** [comment]
Yes, good idea (will also rid us from Pylints `too-many-arguments`). We can just keep `verify_checksum`, which if set to True  implies the current `ignore_checksum` to be False, and by default halts on an error (rather than warn and proceed). What do you think, @chStaiger ?

**Comment by chStaiger** [comment]
I agree. The verify_checksum should be enough for the user to trigger the correct behaviour!
