### ISSUE TITLE
GitHub actions: pylint/python version

### ISSUE THREAD

**Issue by qubixes** [UtrechtUniversity/iBridges#99]
Currently, the python version of the lint workflow is not specified, giving a warning and running it on a unknown version. It also has the wrong name / subname.

In my opinion, pylint should run on all versions of Python (for example it is how I found out that our Python 3.8 support was broken). The advantage of the previous setup was that the run is cancelled if there are pylint issues, saving resources. Also, it reuses the installation (which I guess it doesn't right now?). As far as I understand the main issue was that pylint was holding up the other steps that won't get run.

My suggestion is to put it back in the pylint step into the main build. But that we designate on of the combinations (say Python 3.12) to continue even if the pylint step fails, see e.g.:

https://stackoverflow.com/questions/58858429/how-to-run-a-github-actions-step-even-if-the-previous-step-fails-while-still-f

An idea would also be to make for example to make one of the YoDa/iRods continuous integration tests dependent on one of the packaging tests, to not waste resources there.

**Comment by chStaiger** [comment]
Thanks, I did not think of that! I wrongly assumed that the linting will roughly be the same for all python versions :(

Our integration tests run on python 3.11. So I would say if the linting, mypy and unit tests succeeds for this python version on linux, the integration tests should always be executed. 

For all other python versions we only need to check: linting, mypy, unit tests.

**Comment by qubixes** [comment]
We have agreed that the current setup suffices for now.
